name: flutter_getx_state_management_example
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  http: ^0.13.5
  shared_preferences: ^2.0.18
  email_validator: ^2.1.17
  lazy_load_scrollview: 1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Rick and Morty
      fonts:
        - asset: assets/fonts/rick_and_morty_font.ttf
